### PR TITLE
Moving to sphinx/rtd

### PR DESCRIPTION
**Pull request by AaronSachs**
Hi All, 

Can I request a few specific things in the review? 

* Ensure that all content is present (you can check out the test site http://burnoutio-test.readthedocs.org/en/latest/index.html# )
* Review the contributing guidelines--I want to make sure things are clear and that moving to this framework doesn't discourage people from contributing
* I've pulled some of the resources from @funkatron's site, since they seemed to be a good starting point

If there's anything you think i need to add/remove, please let me know!

### CODE REVIEW

**Comment by bemosior** [comment]
Nothing show-stopping on all points. Looks good! Thank you for your work here.

I'll plan to disable the deployment commit hook before merging. Then we can set up RTD with the domain without disrupting access in the meantime.

I've registered for the RTD beta, but I haven't received access yet. Would you be able to set up the official burnout.io RTD instance? I'm not sure how permissions work with all that, but I think I'd like to work that out before proceeding.

**Comment by AaronSachs** [comment]
Awesome. Yeah, I can work on that--I believe the permissions will be based on whether or not someone's a member of the organization. I'll double check on that. About to step on a plane, but I'll have something in the next day or so.

**Comment by bemosior** [comment]
D'oh, I conflated readthedocs.*com* with readthedocs.*org*. Registering...

**Comment by bemosior** [comment]
Ok, all set up. I've disabled the previous deployment webhook so I can merge this request.

@AaronSachs let me know what your username is on RTD so I can add you as a maintainer (if that's ok with you).

I'll make sure everything looks ok after the merge before pointing the domain to RTD.

**Comment by bemosior** [comment]
Looking good: http://burnoutio.readthedocs.org/en/latest/contribute.html

Opened #36 (badges).

**Comment by bemosior** [comment]
Ok, burnout.io now points to the RTD domain, which appears to work perfectly. Given the record TTL, it may take a bit to take effect everywhere. Overall, looks good!

**Comment by AaronSachs** [comment]
Woot!

**Comment by bemosior** [comment]
Awesome, added you!

**Pull request merged**
